version: "3.3"
services:
  base:
    image: movelai_ws:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
      - UID=${UID:-1000}
      - GID=${UID:-1000}
      - USERNAME=${USERNAME:-devuser}
    privileged: True
    environment:
        - ROS_DISTRO=noetic
        # Needed to define a TurtleBot3 model type
        - TURTLEBOT3_MODEL=${TURTLEBOT3_MODEL:-waffle_pi}
        # Allows graphical programs in the container.
        - DISPLAY=${DISPLAY}
        - QT_X11_NO_MITSHM=1
        - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
        # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # Mount the source code
      - ./src:/movelai_ws/src:rw
      - ./bags:/movelai_ws/bags:rw
      # Mount catkin build artifacts for faster rebuilds
      - ./.catkin/build/:/movelai_ws/build/:rw
      - ./.catkin/devel/:/movelai_ws/devel/:rw
      - ./.catkin/log/:/movelai_ws/log/:rw
    network_mode: host
    user: ${USERNAME:-devuser}
    command: sleep infinity